version: '3'

services:
  web:
    extends:
      file: docker-compose.yml
      service: web
    build:
      target: development
    ports:
      - 24678:24678
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - /workspace/apps/web/node_modules
      - /workspace/packages/config/node_modules
      - /workspace/packages/player/node_modules
      - /workspace/packages/providers/node_modules
      - /workspace/packages/services/node_modules
      - /workspace/packages/ui/node_modules
