version: '3.3'

services:
  web:
    build:
      context: .
      target: production
      args:
        DOCKER_BUILDKIT: 1
    image: cq/web:latest
    restart: always
    env_file:
      - apps/web/.env
    ports:
      - 5173:5173
