version: '3.3'

services:
  web:
    build:
      context: .
    image: clip-queue:latest
    restart: always
    environment:
      VITE_TWITCH_CLIENT_ID: ${VITE_TWITCH_CLIENT_ID}
      VITE_TWITCH_REDIRECT_URI: ${VITE_TWITCH_REDIRECT_URI}
    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - .:/app
