version: '3.3'

services:
  web:
    build:
      context: .
    image: clip-queue-web:latest
    restart: always
    environment:
      VITE_TWITCH_CLIENT_ID: ${VITE_TWITCH_CLIENT_ID}
      VITE_TWITCH_REDIRECT_URI: ${VITE_TWITCH_REDIRECT_URI}
      VITE_SENTRY_DSN: ${VITE_SENTRY_DSN}
    ports:
      - 3000:3000
      - 24678:24678
    volumes:
      - .:/app
