packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.2.2
  '@types/jsdom': ^28.0.1
  '@types/node': ^25.6.0
  '@vitejs/plugin-vue': ^6.0.5
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.9.1
  jsdom: ^29.0.2
  tailwindcss: ^4.2.2
  typescript: ^6.0.2
  vite: ^8.0.8
  vue: ^3.5.32
  vue-tsc: ^3.2.6

catalogs:
  peers:
    vue: ^3.0.0
