packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@tailwindcss/vite': ^4.1.5
  '@types/jsdom': ^21.1.7
  '@types/node': ^22.15.3
  '@vitejs/plugin-vue': ^5.2.3
  '@vue/tsconfig': ^0.7.0
  '@vue/test-utils': ^2.4.6
  jsdom: ^26.1.0
  tailwindcss: ^4.1.5
  typescript: ^5.8.3
  vite: ^6.3.4
  vue: ^3.5.13
  vue-tsc: ^2.2.10

catalogs:
  peers:
    vue: ^3.0.0
