packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@tailwindcss/vite': ^4.0.12
  '@types/jsdom': ^21.1.7
  '@types/node': ^22.13.10
  '@vitejs/plugin-vue': ^5.2.1
  '@vue/tsconfig': ^0.7.0
  '@vue/test-utils': ^2.4.6
  jsdom: ^26.0.0
  tailwindcss: ^4.0.12
  typescript: ^5.8.2
  vite: ^6.2.1
  vue: ^3.5.13
  vue-tsc: ^2.2.8

catalogs:
  peers:
    vue: ^3.0.0
