packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.2.2
  '@types/jsdom': ^28.0.1
  '@types/node': ^25.5.0
  '@vitejs/plugin-vue': ^6.0.5
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.9.0
  jsdom: ^29.0.1
  tailwindcss: ^4.2.2
  typescript: ^5.9.3
  vite: ^8.0.1
  vue: ^3.5.30
  vue-tsc: ^3.2.6

catalogs:
  peers:
    vue: ^3.0.0
