packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.1.11
  '@types/jsdom': ^21.1.7
  '@types/node': ^24.2.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  jsdom: ^26.1.0
  tailwindcss: ^4.1.11
  typescript: ^5.9.2
  vite: ^7.1.1
  vue: ^3.5.18
  vue-tsc: ^3.0.5

catalogs:
  peers:
    vue: ^3.0.0
