packages:
  - 'apps/*'
  - 'packages/*'

catalog:
  '@tailwindcss/vite': ^4.1.7
  '@types/jsdom': ^21.1.7
  '@types/node': ^22.15.21
  '@vitejs/plugin-vue': ^5.2.4
  '@vue/tsconfig': ^0.7.0
  '@vue/test-utils': ^2.4.6
  jsdom: ^26.1.0
  tailwindcss: ^4.1.7
  typescript: ^5.8.3
  vite: ^6.3.5
  vue: ^3.5.14
  vue-tsc: ^2.2.10

catalogs:
  peers:
    vue: ^3.0.0
