packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.1.13
  '@types/jsdom': ^21.1.7
  '@types/node': ^24.3.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  jsdom: ^26.1.0
  tailwindcss: ^4.1.13
  typescript: ^5.9.2
  vite: ^7.1.5
  vue: ^3.5.21
  vue-tsc: ^3.0.6

catalogs:
  peers:
    vue: ^3.0.0
