packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.1.17
  '@types/jsdom': ^27.0.0
  '@types/node': ^24.10.1
  '@vitejs/plugin-vue': ^6.0.1
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  jsdom: ^27.2.0
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  vite: ^7.2.2
  vue: ^3.5.24
  vue-tsc: ^3.1.4

catalogs:
  peers:
    vue: ^3.0.0
