packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.1.11
  '@types/jsdom': ^21.1.7
  '@types/node': ^24.0.15
  '@vitejs/plugin-vue': ^6.0.0
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.7.0
  jsdom: ^26.1.0
  tailwindcss: ^4.1.11
  typescript: ^5.8.3
  vite: ^7.0.5
  vue: ^3.5.17
  vue-tsc: ^3.0.3

catalogs:
  peers:
    vue: ^3.0.0
