packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.1.18
  '@types/jsdom': ^27.0.0
  '@types/node': ^25.2.3
  '@vitejs/plugin-vue': ^6.0.4
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  jsdom: ^28.1.0
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vite: ^7.3.1
  vue: ^3.5.28
  vue-tsc: ^3.2.4

catalogs:
  peers:
    vue: ^3.0.0
