packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.1.18
  '@types/jsdom': ^27.0.0
  '@types/node': ^25.0.2
  '@vitejs/plugin-vue': ^6.0.3
  '@vue/test-utils': ^2.4.6
  '@vue/tsconfig': ^0.8.1
  jsdom: ^27.3.0
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vite: ^7.3.0
  vue: ^3.5.25
  vue-tsc: ^3.1.8

catalogs:
  peers:
    vue: ^3.0.0
