/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/history': RouteRecordInfo<
      '/history',
      '/history',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/integrations/[id]': RouteRecordInfo<
      '/integrations/[id]',
      '/integrations/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/logs': RouteRecordInfo<
      '/logs',
      '/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/queue': RouteRecordInfo<
      '/queue',
      '/queue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | '/settings/application'
      | '/settings/integrations'
      | '/settings/logs'
      | '/settings/other'
      | '/settings/preferences'
    >,
    '/settings/application': RouteRecordInfo<
      '/settings/application',
      '/settings/application',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/integrations': RouteRecordInfo<
      '/settings/integrations',
      '/settings/integrations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/logs': RouteRecordInfo<
      '/settings/logs',
      '/settings/logs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/other': RouteRecordInfo<
      '/settings/other',
      '/settings/other',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/settings/preferences': RouteRecordInfo<
      '/settings/preferences',
      '/settings/preferences',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/history.vue': {
      routes:
        | '/history'
      views:
        | never
    }
    'src/pages/integrations/[id].vue': {
      routes:
        | '/integrations/[id]'
      views:
        | never
    }
    'src/pages/logs.vue': {
      routes:
        | '/logs'
      views:
        | never
    }
    'src/pages/queue.vue': {
      routes:
        | '/queue'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
        | '/settings/application'
        | '/settings/integrations'
        | '/settings/logs'
        | '/settings/other'
        | '/settings/preferences'
      views:
        | 'default'
    }
    'src/pages/settings/application.vue': {
      routes:
        | '/settings/application'
      views:
        | never
    }
    'src/pages/settings/integrations.vue': {
      routes:
        | '/settings/integrations'
      views:
        | never
    }
    'src/pages/settings/logs.vue': {
      routes:
        | '/settings/logs'
      views:
        | never
    }
    'src/pages/settings/other.vue': {
      routes:
        | '/settings/other'
      views:
        | never
    }
    'src/pages/settings/preferences.vue': {
      routes:
        | '/settings/preferences'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
