export {
  ArrowLeftIcon,
  ArrowRightIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingUpIcon,
  BackwardIcon,
  BarsArrowUpIcon,
  ChatBubbleLeftRightIcon,
  Cog8ToothIcon,
  DocumentDuplicateIcon,
  ForwardIcon,
  HandRaisedIcon,
  MoonIcon,
  PlusIcon,
  QueueListIcon,
  SunIcon,
  TrashIcon,
  UserIcon,
  XMarkIcon
} from '@heroicons/vue/24/outline'
