name: Coverage

on:
  push:
    branches:
      - main

jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.1
      - uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run test coverage
        run: pnpm test:coverage
      - name: Upload code coverage to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          flags: unittests
          fail_ci_if_error: true
