name: Run test coverage

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [14]
    steps:
      - name: Setup node version ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Run test coverage
        run: npm run test:coverage
      - name: Upload code coverage to codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./tests/coverage
          flags: unittests
          fail_ci_if_error: true
